#!/usr/bin/env python
import argparse
import os

# Construct the argument parser
ap = argparse.ArgumentParser()
ap.add_argument("hostslist", help="List of IPs on which you want to install NSO, comma separated")
ap.add_argument("-s", "--setupfile", help="Path to setup_data.yml file (Default is ./setup_data.yml)", default="setup_data.yml")
ap.add_argument("-S", "--securesetupfile", help="Path to setup_data_secure.yml file (Default is ./setup_data_secure.yml)", default="setup_data_secure.yml")
ap.add_argument("-t", "--steps", help="Steps you want to perform, comma separated  (Default is all, accepted values are are all or a combination of one or more of the following: install-linux-packages, install-NSO, install-NEDs, install-repository-packages, setup-netsim and setup-HA)", default="all")
args= ap.parse_args()
if args.steps == "all" :
	tags=""
else :
        validvalues=['install-linux-packages', 'install-NSO', 'install-NEDs', 'install-repository-packages', 'setup-netsim', 'setup-HA']
        stepslist=args.steps.split(",")
        for step in stepslist:
		if step not in validvalues :
                	print "Error: "+step+" is not a valid step\nPlease only enter all or a combination of the following: install-linux-packages, install-NSO, install-NEDs, install-repository-packages, setup-netsim and setup-HA"
        		exit()
	tags=" --tags="+args.steps
os.system("ansible-playbook -i "+args.hostslist+", --extra-vars '{\"setup_data\":\""+args.setupfile+"\",\"setup_data_secure\":\""+args.securesetupfile+"\"}' --ask-vault-pass"+tags+" aNSOble.yml") 
