- hosts: servers
  vars_files:
    - 'setup_data.yml'
    - 'setup_data_secure.yml'
  roles:
    - { role: install-linux-packages, tags: [ 'install-linux-packages' ] }
    - { role: install-NSO, tags: [ 'install-NSO' ] }
    - { role: install-NEDs, tags: [ 'install-NEDs' ] }
    - { role: install-repository-packages, tags: [ 'install-repository-packages' ] }
    - { role: setup-HA, tags: [ 'setup-HA' ] , when: SetupHA }
