- hosts: all
  vars:
     mode: "{{mode}}"
     device: "{{device}}"
     config: "{{config}}"
     NEW_NEDs: "{{NEW_NEDs}}"
  vars_files:
    - setup_data.yml
  environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ncs/current/bin" 
  roles:
    - { role: install-linux-packages, tags: [ 'install-linux-packages' ] }
    - { role: install-NSO, tags: [ 'install-NSO' ] , when: NSOInstallType is defined }
    - { role: install-NEDs, tags: [ 'install-NEDs' ] }
    - { role: install-repository-packages, tags: [ 'install-repository-packages' ] , when RepositoryURL is defined }
    - { role: setup-netsim, tags: [ 'setup-netsim' ] , when: NetsimDevices is defined }
    - { role: setup-HA, tags: [ 'setup-HA' ] , when: SetupHA }
    - { role: data_collector, tags: [ 'data_collector' ] }
    - { role: device_check_sync_from, tags: [ 'device_check_sync_from' ] }
    - { role: enable_disable_HA, tags: [ 'enable_disable_HA' ] }
    - { role: backup_restore_NSO, tags: [ 'backup_restore_NSO' ] }
    - { role: compact_CDB, tags: [ 'compact_CDB' ] }
    - { role: device_migration, tags: [ 'device_migration' ] }
    - { role: config_NSO, tags: [ 'config_NSO' ] }
    - { role: copy_master_to_slave, tags: [ 'copy_master_to_slave' ] }
