- hosts: all
  vars_files:
    - setup_data.yml
  vars:
    mode: "{{mode}}"
  environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ncs/current/bin" 
  roles:
    - { role: install-linux-packages, tags: [ 'install-linux-packages' ] }
    - { role: install-NSO, tags: [ 'install-NSO' ] , when: NSOInstallType is defined }
    - { role: install-NEDs, tags: [ 'install-NEDs' ] , when: NEDs is defined }
    - { role: install-repository-packages, tags: [ 'install-repository-packages' ] , when RepositoryURL is defined }
    - { role: setup-netsim, tags: [ 'setup-netsim' ] , when: NetsimDevices is defined }
    - { role: setup-HA, tags: [ 'setup-HA' ] , when: SetupHA }
    - { role: data_collector, tags: [ 'data_collector' ] }
