
- name: Downloading Tailf-HCC-Project from the earth repo
  shell: wget -k --secure-protocol=TLSv1 -v --no-check-certificate --user {{ NEDsRepoUser }} --password {{ NEDsRepoPass }} https://earth.tail-f.com:8443/ncs-pkgs/tailf-hcc-project/{{ TailfHCCNSOVersion }}/ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-project-{{ TailfHCCVersion }}.signed.bin >> /tmp/aNSOble.log
  args:
    chdir: /tmp/
    warn: false
  become: true

- name: Executing unpacking of signed Tailf-HCC-Project
  shell: |
    chmod 0755 ./ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-project-{{ TailfHCCVersion }}.signed.bin >> /tmp/aNSOble.log
    ./ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-project-{{ TailfHCCVersion }}.signed.bin >> /tmp/aNSOble.log
  args:
    chdir: /tmp/
    warn: false
  become: true

- name: Unpacking Tailf-HCC-Project into /tmp
  shell: tar zxvf ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-project-{{ TailfHCCVersion }}.tar.gz -C /tmp >> /tmp/aNSOble.log
  args:
    chdir: /tmp/
    warn: false
  become: true

- name: Unpacking Tailf-HCC  into /var/opt/ncs/packages
  shell: tar zxvf ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-{{ TailfHCCVersion }}.tar.gz -C /var/opt/ncs/packages >> /tmp/aNSOble.log
  args:
    chdir: /tmp/ncs-{{ TailfHCCNSOVersion }}-tailf-hcc-project-{{ TailfHCCVersion }}/packages
    warn: false
  become: true

- name: Reloading NSO packages
  shell: |
    source /opt/ncs/current/ncsrc
    echo 'packages reload' | ncs_cli -C
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}

- name: Addition of primary and secondary entries in /etc/hosts 
  blockinfile:
    path: /etc/hosts
    marker: "## {mark} Added by ansible (setting up hosts)"
    block: |
      primary {{ PrimaryIP }}
      secondary {{ SecondaryIP }}
  become: true

- name: Setup of HA as Enable in /etc/ncs/ncs.conf 
  blockinfile:
    path: /etc/ncs/ncs.conf
    marker: "<!-- {mark} Added by ansible (setting up hosts) -->"
    insertbefore: "</ncs-config>"
    block: |
        <ha>
          <enabled>true</enabled>
        </ha>
  become: true

- name: Restart NSO service
  shell: |
    source /etc/profile.d/ncs.sh
    /etc/init.d/ncs restart >> /tmp/aNSOble.log
  become: true

- name: Creating the HA config file from template
  template:
    src: ha.j2
    dest: /home/{{ ansible_user }}/ha.xml

- name: Loading HA config
  shell: ncs_load -l -m ha.xml
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}

- name: Activating HA
  shell: |
    source /opt/ncs/current/ncsrc
    echo 'request ha commands activate' | ncs_cli 
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}  
