---
# vars file for vmware_ubuntu_cloud_image

static_ipv4: "{{ static_ip.ipv4 }}"
netmask: "{{ static_ip.netmask }}"
gateway: "{{ static_ip.gateway }}"
dns_servers: "{{ static_ip.dns_servers | default([8.8.8.8]) }}"
dns_search: "{{ static_ip.dns_search | default([]) }}"
vm_guestname: "{{ vm_name }}"
vm_hostname: "{{ vm_name }}"
guest_user: "{{ ansible_user }}"
guest_pw: "{{ ansible_password }}"

# vim: ts=2:sw=2:noautoindent:nosmartindent
