- name: Stop NSO
  shell: ncs --stop >> aNSOble.log
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
  ignore_errors: yes
  become: true

- name: Uninstall NSO
  shell: ncs-uninstall --all --non-interactive >> /tmp/aNSOble.log
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
  become: true
