
  - name: List the device groups 
    shell:  echo "show devices device-group member" | ncs_cli -C | awk -F'[][]' '{print $2}' | uniq | awk NF
    register: out1

  - shell: echo "{{NEW_NEDs}}"
    register: out2

  - name: run migrate command
    shell: |
        for i in {{item[0]}};
        do
          echo "devices device $i migrate new-ned-id {{item[1]}} no-networking wait-for-lock { infinity }" | ncs_cli -C;
        done;
    with_nested:
          - "{{out1.stdout_lines}}"
          - "{{out2.stdout_lines}}"

