      - name: Stop NSO
        include_role:
               name: stop_NSO
      - name: Fetch NCS_DIR
        shell: /bin/bash -l -c 'env' | grep NCS_DIR | awk -F "=" '{print $2}'
        register: NCS_DIR
      - set_fact:
              NCS_DIR: "{{NCS_DIR.stdout}}"
      - name: Run CDB compact command
        shell: {{NCS_DIR}}/bin/ncs --cdb-compact {{CDB_DIR}}
        register: out1
        become: true
      - debug:
          msg: "{{out1.stdout}}"
      - name: Start NSO service
        include_role: 
               name: start_NSO
