- name: Check if there are running Netsim devices
  stat:
    path: /var/opt/ncs/packages/netsim
  register: netsim_dir

- name: Stop and delete existing Netsim devices
  shell: ncs-netsim delete-network >> /tmp/aNSOble.log 2>&1
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
    NCS_DIR: /opt/ncs/current
  args:
    chdir: /var/opt/ncs/packages/
  when: netsim_dir.stat.exists

- name: Create Netsim Devices
  shell: |
    source /opt/ncs/current/ncsrc
    ncs-netsim {{  "create-network" if item.name == NetsimDevices[0].name  else "add-to-network" }} {{item.name}} {{item.numberofDevices}} {{item.deviceNamePrefix}} >> /tmp/aNSOble.log
  args:
    chdir: /var/opt/ncs/packages/
    executable: /bin/bash
  loop: "{{ NetsimDevices }}"

- name: Starting Netsim devices
  shell: ncs-netsim start >> /tmp/aNSOble.log 2>&1
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
    NCS_DIR: /opt/ncs/current
  args:
    chdir: /var/opt/ncs/packages/

- name: Generating Netsim devices NSO config
  shell: ncs-netsim ncs-xml-init > ~/devices-config.xml 
  args:
    chdir: /var/opt/ncs/packages/
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
    NCS_DIR: /opt/ncs/current

- name: Load Netsim devices config
  shell: ncs_load -l -m devices-config.xml >> /tmp/aNSOble.log
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
    NCS_DIR: /opt/ncs/current

- name: Executing sync-from Netsim devices
  shell: echo 'devices device * sync-from' | ncs_cli -C >> /tmp/aNSOble.log
  environment:
    PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
    NCS_DIR: /opt/ncs/current
