
- name: Installing GIT
  package:
    name: git 
    state: present
  become: true

- name: Installing python
  package:
    name: python2 
    state: present
  become: true

- name: Installing java  
  package:
    name: java 
    state: present
  become: true

- name: Setup default python version
  shell: alternatives --set python /usr/bin/python3
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
