- name: Creating log file
  file: 
    path=/tmp/aNSOble.log 
    state=touch

- name: Update apt cache
  apt:
    update-cache: true
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: Installing Linux Packages
  package:
    name: "{{ item }}" 
    state: present
  become: true
  loop: "{{ linuxPackages }}"
  when: linuxPackages is defined

- name: Setup default python version
  shell: alternatives --set python /usr/bin/python3
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
