 - name: Running block for backup
   block:
    - name: Run ncs-backup command
      shell: ncs-backup 
      register: out1
      become: true
    - debug:
        msg: "{{out1.stdout}}"
    - shell: echo "{{out1.stdout}}" | awk '{print $3}'
      register: out2
    - set_fact:
          Backup_file: "{{out2.stdout}}"
    - debug:
          msg: "Backup file is {{Backup_file}}"
   when: ( mode == 'backup' )

 - name: Running block for restore
   block:
      - name: Stop NCS process to run restore
        shell: ncs --stop >> /tmp/aNSOble.log
        environment:
              PATH: /opt/ncs/current/bin:{{ ansible_env.PATH }}
        ignore_errors: yes
        become: true
      - name: Pick the latest Backup file, Please restore manually in case of particular backup file restoration
        shell: ls -rt /var/opt/ncs/backups/ | tail -n 1
        register: out3
      - set_fact:
             Backup_file: "{{out3.stdout}}"
      - name: run restore command
        shell:  yes | ncs-backup --restore {{Backup_file}}
        register: out4
        ignore_errors: true
        become: true
      - debug:
          msg: "{{out4.stdout}}"
      - name: Start NSO service
        shell: |
           source /etc/profile.d/ncs.sh
           /etc/init.d/ncs start >> /tmp/aNSOble.log 2>&1
        become: true
   when: ( mode == 'restore' ) 
