---
 - hosts: localhost
   vars:
       HOST: "{{dest_host}}"
       USER: "{{dest_user}}"
       PASS: "{{dest_pass}}"
   vars_files:
    - setup_data.yml

   tasks:
      - name: Copy {{LOG_DIR}}/job_templates.json from {{AWX_HOST}} to {{HOST}} at {{LOG_DIR}} 
        shell: |
             sshpass -p {{PASS}} sudo scp  -o StrictHostKeyChecking=no -r {{LOG_DIR}}/job_templates.json {{USER}}@{{HOST}}:{{LOG_DIR}}/

 - hosts: "{{NEW_AWX_HOST}}"
   vars_files:
    - setup_data.yml
   environment:
        PATH: "{{ ansible_env.PATH }}:~/.local/bin"
   tasks:
      - shell:  pip3 install awxkit
        ignore_errors: true
      - name: importing templates from {{AWX_HOST}} at {{LOG_DIR}} on local
        shell: |         
             awx import --conf.host http://{{NEW_AWX_HOST}}/ --conf.username {{NEW_AWX_USER}} --conf.password {{NEW_AWX_PASS}} -k -f json job_templates < job_templates.json
        args:
            chdir: "{{LOG_DIR}}"
