- name: Install prerequisites for Docker repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: yes
    install-recommends: yes
  become: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  become: yes

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    install-recommends: yes
  become: yes

- name: Allow user access to Docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes